version: "3.8"

services:
  adminvault:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adminvault_app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: always
