services:
  - type: web
    name: adminvault-backend
    runtime: node
    buildCommand: npm install && npx tsc --build packages/libs/shared-models/tsconfig.lib.json && npx tsc --build packages/libs/backend-utils/tsconfig.lib.json && npx nx build backend --configuration=production
    startCommand: node dist/backend/main.js
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: NODE_ENV
        value: production
