services:
  - type: web
    name: adminvault-backend
    env: node
    region: oregon
    buildCommand: npm install && npm run build:backend
    startCommand: node dist/packages/backend/main.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
